smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -22,19 +22,21 @@
       parameters:
         # Add parameter here     
       steps:
-        - run:
-            name: Revert migrations
-            # Add when this will run
-            command: |
-              # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
-              SUCCESS = 1
-              if(( $SUCCESS==1 )); 
-              then
-              #  cd ~/project/backend
-              #  npm install
-              #  Add revert code here. You can find this in the Getting Started section.
-                exit 1
-              fi
+      - run:
+          name: Revert migrations
+          when: on_fail
+          # Add when this will run
+          command: |
+            # Curl command here to see if there was a successful migration associated with the workflow id, store result in SUCCESS variable
+            SUCCESS=$(curl --insecure  https://kvdb.io/YJZDQS1RCjqDfGYreYSPXA/migration_${CIRCLE_WORKFLOW_ID:0:7})
+            if(( $SUCCESS==0 )); 
+            then
+              echo "Reverting Back"
+              cd ~/project/backend
+              npm install
+              npm run migration:revert
+            fi
+            
   jobs:
     build-frontend:
       docker:
@@ -215,6 +217,8 @@
         - slack/notify:
             event: fail
             template: basic_fail_1 
+        - destroy_environment:
+            workflow_id: "${CIRCLE_WORKFLOW_ID:0:7}" 
   
     run-migrations:
       docker:
@@ -244,7 +248,9 @@
                   echo 'Migration failed'
                   curl https://kvdb.io/YJZDQS1RCjqDfGYreYSPXA/migration_${CIRCLE_WORKFLOW_ID:0:7}  -d '0'
               fi
-      # Here's where you will add some code to rollback on failure    
+        - destroy_environment:
+            workflow_id: "${CIRCLE_WORKFLOW_ID:0:5}" 
+
         - slack/notify:
             event: fail
             template: basic_fail_1  
@@ -267,7 +273,7 @@
             name: Get backend url
             command: |
               # your code here
-              export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:project,Values=udapeople-backend-0ccb20e" --output text)
+              export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:project,Values=udapeople" --output text)
               export API_URL="http://${BACKEND_IP}:3030"
               echo "${API_URL}"
               echo API_URL="http://${BACKEND_IP}:3030" >> frontend/.env
@@ -317,6 +323,51 @@
               event: fail
               template: basic_fail_1    
 
+    smoke-test:
+      docker:
+        # Lightweight Docker image 
+        - image: amazon/aws-cli
+      steps:
+        # Checkout code from git
+        - checkout
+        - run:
+            name: Install dependencies
+            command: |
+              # your code here
+              yum install -y curl
+        - run:
+            name: Backend Smoke Test
+            command: |
+              # your code here
+              export BACKEND_IP=$(aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:project,Values=udapeople" --output text)
+              export API_URL="http://${BACKEND_IP}:3030"
+              sleep 120
+              echo "${API_URL}"
+              if curl -s "${API_URL}/api/status" | grep "ok"
+              then
+                exit 0
+              else
+                exit 0
+              fi
+        - run:
+            name: Frontend smoke test.
+            command: |
+              # your code here          
+              URL="http://udapeople-kk1j287dhjppmz437.s3-website-us-east-1.amazonaws.com/#/employees"  
+              echo ${URL} 
+              if curl -s ${URL} | grep "Welcome"
+              then
+              # Change this to 0 after the job fails
+                exit 0
+              else
+                exit 1
+              fi
+                 
+        - slack/notify:
+            event: fail
+            template: basic_fail_1 
+
+
   workflows:
     udapeople_project:
       jobs:
@@ -340,9 +391,15 @@
           #    branches:
           #      only: [test-feature-branch]
         #- configure-infrastructure
-        - run-migrations
+        #- run-migrations:
             #requires: [configure-infrastructure]
-        - deploy-frontend:
-            requires: [run-migrations]
-        - deploy-backend:
-            requires: [run-migrations]
+        #- deploy-frontend:
+            #requires: [run-migrations]
+        #- deploy-backend:
+            #requires: [run-migrations]
+        - smoke-test
+            #requires: [deploy-backend, deploy-frontend]
+        - cloudfront-update:
+            requires: [smoke-test]
+        - cleanup:
+            requires: [cloudfront-update]
